name: main

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: Clone algolia repository
      uses: actions/checkout@v2
      with:
        repository: algolia/docsearch-scraper
        path: algolia

    - name: Install requirements
      run: |
        pip install Scrapy==2.2.1
        pip install pyperclip==1.5.27
        pip install python-dotenv==0.7.1
        pip install ratelimit==1.4.1
        pip install selenium==3.141.0
        pip install slacker==0.9.60
        pip install tldextract==2.1.0
        pip install pytest==3.10.0
        pip install requests-iap==0.2.0
        pip install python-helpscout-v2==1.0.1
        pip install algoliasearch

    - name: Prepare the algolia
      run: |
        ls .
        cd algolia
        mv .env.example .env
        echo { > config.json
        echo   "index_name": "hardwario", >> config.json
        echo   "start_urls": [ >> config.json
        echo     "https://docs.hardwario.com/" >> config.json
        echo   "stop_urls": [], >> config.json
        echo   "selectors": { >> config.json
        echo     "lvl0": "h1", >> config.json
        echo     "lvl1": "h2", >> config.json
        echo     "lvl2": "h3", >> config.json
        echo     "lvl3": "h4", >> config.json
        echo     "lvl4": "h5", >> config.json
        echo     "lvl5": "h6", >> config.json
        echo     "text": "p, li" >> config.json
        echo   } >> config.json
        echo } >> config.json
        cat config.json

    - name: Build The Search
      run: |
        chmod +x algolia/docsearch
        cd algolia ; ./docsearch run config.json
