name: main

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
    steps:
    - uses: actions/checkout@v3

    - name: Clone algolia repository
      uses: actions/checkout@v2
      with:
        repository: algolia/docsearch-scraper
        path: algolia

    - name: Prepare the algolia
      run: |
        ls .
        cd algolia
        mv .env.example .env
        echo { > config.json
        echo   "index_name": "hardwario", >> config.json
        echo   "start_urls": [ >> config.json
        echo     "https://docs.hardwario.com/" >> config.json
        echo   "stop_urls": [], >> config.json
        echo   "selectors": { >> config.json
        echo     "lvl0": "h1", >> config.json
        echo     "lvl1": "h2", >> config.json
        echo     "lvl2": "h3", >> config.json
        echo     "lvl3": "h4", >> config.json
        echo     "lvl4": "h5", >> config.json
        echo     "lvl5": "h6", >> config.json
        echo     "text": "p, li" >> config.json
        echo   } >> config.json
        echo } >> config.json
        cat config.json

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Build The Search
      run: |
        cd algolia
        ls .
        chmod +x docsearch
        pipenv install
        pipenv run ./docsearch run config.json














